# ----------------------- #
# Site
# ----------------------- #

title: PostgreSQL Portable
author: Gareth Flowers

# ----------------------- #
# Jekyll
# ----------------------- #

markdown: redcarpet
exclude:  [ Gemfile, Gemfile.lock, README.md, vendor/ ]
gems:
  - jekyll-sitemap
